### ISSUE TITLE
Parsing "{{ 'nowutc' | as_date | date_offset:'1 day' | date:'yyyy-MM-ddT00:00:00Z' }}" returns today's date instead of tomorrow's date

### ISSUE THREAD

**Issue by icnocop** [Pathoschild/NaturalTimeParser#10]
Hi.

Parsing `{{ 'nowutc' | as_date | date_offset:'1 day' | date:'yyyy-MM-ddT00:00:00Z' }}` returns today's date instead of tomorrow's date.

My current time zone is PDT = GMT - 7 (DST)
My current date and time is 5/30/2019 2:30 PM.

The date and time in GMT is 5/30/2019 9:30 PM.

So I expected parsing `{{ 'nowutc' | as_date | date_offset:'1 day' | date:'yyyy-MM-ddT00:00:00Z' }}` to return 5/31/2019, but it actually returns 5/30/2019.

Any ideas?

Thank you.

**Comment by icnocop** [comment]
Sorry, this is my fault.

I was using `DateTime.Parse(output)` instead of `DateTimeOffset.Parse(output)`.

😉

**Comment by Pathoschild** [comment]
Glad you found the issue!
