### ISSUE TITLE
Support parsing date time strings

### ISSUE THREAD

**Issue by ramiabughazaleh** [Pathoschild/NaturalTimeParser#5]
I'd like TimeParser to be able to parse date time strings that have already been created by calling `DateTime.ToString()`.

For example,
```
TimeParser timeParser = new TimeParser();
DateTime dateTime = DateTime.UtcNow;
string dateTimeAsString = dateTime.ToString(CultureInfo.InvariantCulture);
DateTime parsedDateTime = timeParser.Parse(dateTimeAsString);
Assert.AreEqual(dateTime, parsedDateTime);
```

Thank you.

**Comment by Pathoschild** [comment]
Hi @ramiabughazaleh. That's not needed because `DateTime` has a full-featured parse method built-in:
```cs
DateTime date = DateTime.UtcNow;
string dateString = date.ToString(CultureInfo.InvariantCulture);
DateTime parsedDate = DateTime.Parse(dateString, CultureInfo.InvariantCulture);
Assert.AreEqual(date, parsedDate);
```

`DateTime::Parse` handles many scenarios that would be out of scope for this project (like custom date formats, different cultures and calendars, etc).
